# Site settings
author:
  name: "Chaitanya Kundety"
  email: "chaitanyakun@outlook.com"
title: "Chaitanya Kundety | Portfolio"
email: chaitanyakun@outlook.com
description: "A portfolio website showcasing my projects, education, and skills."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ckundety.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Include the following paths in the Jekyll build
include:
  - _pages

# Exclude the following paths from the Jekyll build
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Configuring plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Enabling GitHub Pages gem
github: 
  is_project_page: true

# Additional configurations
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

# Enabling relative permalinks
relative_permalinks: true

# SEO settings
seo:
  title: "{{ page.title | default: site.title }}"
  description: "{{ page.excerpt | default: site.description }}"
  url: "{{ site.url }}{{ site.baseurl }}"